"""empty message

Revision ID: 99872db6023c
Revises: 
Create Date: 2025-08-07 14:43:52.735816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99872db6023c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_name', sa.String(), nullable=True),
    sa.Column('salary', sa.Boolean(), nullable=True),
    sa.Column('need_lvl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('lvl', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Boolean(), nullable=True),
    sa.Column('work', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work'], ['work.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('work')
    # ### end Alembic commands ###
